### ISSUE TITLE
PlayNotes support

### ISSUE THREAD

**Issue by carks32** [HerrKnarz/Playnite-Theme-KNARZnite#1]
[Darklink recently released this funny](https://playnite.link/addons.html#PlayNotes_4208657d-4f78-42d2-968f-39f24de275e1) addon and I spent a bit of time on it and it seems mad useful, dunno if it's possible to integrate it into this theme though, only tried with the themes darklink has made.

**Comment by HerrKnarz** [comment]
I just released version 1.3 of the theme that includes support for PlayNotes among other addons.
