### ISSUE TITLE
Tags not showing up

### ISSUE THREAD

**Issue by Ezrile** [HerrKnarz/Playnite-Theme-KNARZnite#4]
Tags & Genre aren't showing at all within detail view after the recent update.

Edit: Solved it myself. Something wasn't installed.

**Comment by HerrKnarz** [comment]
Yeah, the new version uses Metadata Utilities to display tags and similar fields. I'll write a quick tutorial on how to use the extended features that come with the change in the next days.

**Comment by Chomping** [comment]
How did you solve it? I have the same problem, I have Metadata Utilities installed, do I need to do anything else? 

In the meantime I will continue with 1.6 because I like the option to show the tags as a box.

**Comment by Ezrile** [comment]
> How did you solve it? I have the same problem, I have Metadata Utilities installed, do I need to do anything else?
> 
> In the meantime I will continue with 1.6 because I like the option to show the tags as a box.

I can only get them to show up as a list. I don't think you can change it back to box, unless there is some way I'm unaware of.

**Comment by Chomping** [comment]
> I can only get them to show up as a list. I don't think you can change it back to box, unless there is some way I'm unaware of.
I meant that I don't even have them as a list.

**Comment by Ezrile** [comment]
> > I can only get them to show up as a list. I don't think you can change it back to box, unless there is some way I'm unaware of.
> 
> I meant that I don't even have them as a list, how did you get them to show?.
Do you have them checked under settings for details view?

**Comment by Chomping** [comment]
> Do you have them checked under settings for details view?

of course, they were showing fine before upgrading

![Captura de pantalla 2024-10-14 230850](https://github.com/user-attachments/assets/ca673820-22cb-482f-8235-3816ef4f9a7c)

Do I have to do anything extra in metadata utilities?

**Comment by HerrKnarz** [comment]
What version of Metadata Utilities are you using? It has to be at least version 1.3. Apart from that you shouldn't need to do anything.

The option to display the items as a box will return, but I'm not sure when and how I'll implement it, however.

**Comment by HerrKnarz** [comment]
Ah, wait a minute. I have an idea, what's wrong. You have Playnite translated. I think I used the field names for the controls, and it could be that I used the already translated string. That wouldn't work anymore, if tags aren't called tags anymore ;) - I'll open the issue again and work on a fix in the addon and the theme.

**Comment by Chomping** [comment]
> Ah, wait a minute. I have an idea, what's wrong. You have Playnite translated. I think I used the field names for the controls, and it could be that I used the already translated string. That wouldn't work anymore, if tags aren't called tags anymore ;) - I'll open the issue again and work on a fix in the addon and the theme.

![Captura de pantalla 2024-10-18 151953](https://github.com/user-attachments/assets/e12bb0d0-0c07-41e4-991b-96960c0a384a)

Yeah, It is the language.

**Comment by HerrKnarz** [comment]
I just fixed it in Metadata Utilities. If everything goes to plan, I'll release the new version later today or tomorrow.

**Comment by Chomping** [comment]
> I just fixed it in Metadata Utilities. If everything goes to plan, I'll release the new version later today or tomorrow.

Has been fixed with the update. Thank you.
