### ISSUE TITLE
[Enhancement] Switcher for play status

### ISSUE THREAD

**Issue by chocolatechipcats** [HerrKnarz/Playnite-Theme-KNARZnite#5]
One feature from darklinkpower's Mythic theme that I miss is this:

![2024-10-09 20_59_53-Playnite](https://github.com/user-attachments/assets/9a4e60e9-e319-421d-930e-944c9d5bcc0a)

I don't know if it would be feasible to include it in KNARZnite but I think it would be useful if so.

**Comment by HerrKnarz** [comment]
I think that#s part of the Theme Extras addon. I'll see, if it's easy to implement!

**Comment by HerrKnarz** [comment]
Added in version 2.0

**Comment by chocolatechipcats** [comment]
Yay!
