### ISSUE TITLE
Help with finding the correct reference in DetailsViewGameOverview.xaml for Date Added

### ISSUE THREAD

**Issue by woutercools** [HerrKnarz/Playnite-Theme-KNARZnite#7]
I'm sorry for posting this here, but I've already tried getting an answer on Reddit, Discord and with Josef himself without success.

I want to add the date when a game was added to my database to the DetailsViewGameOverview.xaml, but I can't find the correct resource.

More info here: https://github.com/JosefNemec/PlayniteExtensions/issues/419

Can you help me which code gives me the Added Date on the Game Overview screen?

Thanks.

**Comment by HerrKnarz** [comment]
You don't need to change anything in the theme. Just tick the checkbox for Date added in the Settings under Details View and it should appear, if the game has a date in the database.

**Comment by woutercools** [comment]
OMG!!!

Thank you for this realization.
I've been struggling with this for weeks.

Thanks again.
